config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    post 'join_team', to: 'event_players#create_or_update', as: :join_team
  end

  patch 'free_agent_true', to: 'users#free_agent_true', as: :free_agent_true
  patch 'free_agent_false', to: 'users#free_agent_false', as: :free_agent_false
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :event_players, dependent: :destroy

  has_many :players, through: :event_players, class_name: 'User'
  has_many :teams, dependent: :destroy

  before_save :set_name
  after_create :set_teams


  private

  def set_name
    self.name = name[0].upcase + name[1..-1]
  end

  def set_teams
    team_a = teams.create!(name: 'Equipe 1')
    teams.create!(name: 'Equipe 2')
    teams.create!(name: 'Sur le banc')
    event_players.create!(player: author, team: team_a)
  end
end

app/models/event_player.rb
class EventPlayer < ApplicationRecord
  belongs_to :event
  belongs_to :player, class_name: 'User'
  belongs_to :team

  validate :validate_max_players, on: :create

  private

  def validate_max_players
    # Compter uniquement les joueurs des deux premières équipes
    teams_in_play = event.teams.limit(2)
    player_count = EventPlayer.where(event: event, team: teams_in_play).count

    if player_count >= event.max_players
      errors.add(:base, "Nombre maximum de joueurs atteint pour cet événement.")
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :event_players
  has_many :players, through: :event_players, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :event_players, dependent: :destroy
  has_many :events, through: :event_players
  has_many :teams, through: :event_players

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, class_name: 'User'

  before_save :set_username


  private

  def set_username
    self.first_name.capitalize!
    self.last_name.upcase!
    random_number = rand(1000..9999)
    loop do
      self.username = "#{first_name}#{last_name[0]}##{random_number}"
      break unless User.exists?(username: self.username)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/event_players_controller.rb
class EventPlayersController < ApplicationController
  def create_or_update
    @event = Event.find(params[:event_id])
    @event_player = EventPlayer.find_or_initialize_by(event: @event, player: current_user)
    @event_player.team_id = event_player_params[:team_id]
    @team = @event_player.team
    if @event_player.save
      redirect_to event_path(@event)
    end
  end

  private

  def event_player_params
    params.require(:event_player).permit(:team_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.includes(event_players: :player).order(:start_time)
  end

  def show
    @event = Event.find(params[:id])
    @event_player = EventPlayer.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_event)
    @event.author = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    redirect_to event_path(@event) if @event.update(params_event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def params_event
    params.require(:event).permit(:name, :location, :start_time, :price, :max_players)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def free_agent_true
    @user = current_user
    if @user.update(set_free_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    end
  end

  def free_agent_false
    @user = current_user
    if @user.update(set_free_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    end
  end

  private

  def set_free_params
    params.require(:user).permit(:free_agent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_players_helper.rb
module EventPlayersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<%= turbo_frame_tag 'edit-title' do %>
  <%= form_with model: @event do |f| %>
    <%= f.text_field :name, autofocus: true, class: "form-field"  %>
    <%= f.submit '✔️', id: 'form-submit-btn' %>
  <% end %>
<% end %>

<%= turbo_frame_tag 'edit-location' do %>
  <%= form_with model: @event do |f| %>
    <%= f.text_field :location, autofocus: true, class: "form-field"  %>
    <%= f.submit '✔️', id: 'form-submit-btn' %>
  <% end %>
<% end %>

app/views/events/index.html.erb
<h1>Les prochains événements futsal</h1>

<%= link_to 'Créer un nouvel événement futsal', new_event_path, id: 'cta-btn' %>

<section id="events-grid-container">
  <% @events.each do |event| %>
    <%= render 'events/index/event-card', event: event %>
  <% end %>

</section>

app/views/events/index/_event-card.html.erb
<div class="event-card">
  <%= link_to event_path(event) do %>
    <div class="event-content">

      <h2>
        <%= event.name %>
      </h2>

      <div>
        <p class="text-white">
          <%= event.location %>
        </p>

        <p class="text-white">
          <%= l event.start_time, format: :date %>
          <br>
          <%= l event.start_time, format: :hour %>
        </p>
      </div>

      <p class="<%= event.players.length < event.max_players ? "green-team" : "red-team" %>">
        <%= event.players.length %>/<%= event.max_players %> joueurs
      </p>

    </div>

  <% end %>
</div>

app/views/events/new.html.erb
<h1>Créer mon événement futsal</h1>

<%= form_with model: @event do |f| %>

  <div>
    <%= f.label :name, 'Nom de l\'événément' %>
    <div class="form-input">
      <%= f.text_field :name, value: "futsal by #{current_user.username}", autofocus: true, class: "form-field"  %>
    </div>
  </div>

  <div>
    <%= f.label :location,'Où ?' %>
    <div class="form-input">
      <%= f.text_field :location, placeholder: '13 By Puma', value: '13 By Puma', class: "form-field" %>
    </div>
  </div>

    <%= f.label :start_time, 'Quand ?' %>
    <% # Calcul du vendredi suivant
      next_friday = Time.now + ((5 - Time.now.wday) % 7).days
    %>
    <div class="form-input">
      <%= f.datetime_field :start_time, value: next_friday.strftime("%Y-%m-%dT%H:%M"), class: "form-field" %>
    </div>

    <%= f.label :max_players, 'Nombre de joueurs total ?' %>
    <div class="form-input">
      <%= f.number_field :max_players, value: 10, class: "form-field" %>
    </div>

    <%= f.label :price, 'Prix par joueur ?' %>
    <div class="form-input">
      <%= f.number_field :price, value: 10, class: "form-field" %>
    </div>

    <div class="form-submit">
      <%= f.submit 'Créer mon événement futsal', id: 'form-submit-btn' %>
    </div>

<% end %>

app/views/events/show.html.erb
<h1>
  <%= turbo_frame_tag 'edit-title' do %>
    <%= @event.name %>
    <%= link_to '✏️', edit_event_path(@event) %>
  <% end %>
</h1>

<%= render 'events/show/event-info', event: @event %>

<%= render 'events/show/teams-container', event: @event %>

<div class="text-center">
  <%= link_to event_path(@event), data: {turbo_method: :delete, turbo_confirm: "tu es sûr?"} do %>
    <button id="delete-btn">Annuler le futsal</button>
  <% end %>
</div>

app/views/events/show/_each-players.html.erb
<% team.players.each do |player| %>
  <div class="player-card player-card-<%= i + 1 %>" >
    <%= player.first_name %>
  </div>
<% end %>

<% unless team.players.include?(current_user) %>
  <%= form_with model: [ event, event_player ], url: event_join_team_path(event), turbo_method: :post do |f| %>
    <%= f.hidden_field :team_id, value: team.id %>
    <%= f.submit "Rejoindre", class: 'join-team-cta' %>
  <% end %>
<% end %>

app/views/events/show/_event-info.html.erb
<%= turbo_frame_tag 'edit-location', class: 'event-info' do %>
  <%= @event.location %>
  <%= link_to '✏️', edit_event_path(@event) %>
  <% end %>

<div class='event-info'>
  <%= l @event.start_time, format: :date %> <br>
  <%= l @event.start_time, format: :hour %>
</div>

<div class='event-info'>
  <%= number_to_currency(@event.price, unit: "€", separator: ",", delimiter: " ", format: "%n %u") %> / joueur
</div>

<div class="container-flex-center <%= event.players.length < event.max_players ? "green-team" : "red-team" %>">
  <div class='event-info'>
    <%= @event.players.length %>
  </div>

  <div class="event-info-slash">
    /
  </div>

  <div class="event-info">
    <%= @event.max_players %> joueurs
  </div>
</div>

<div class='event-info'>
  créé par <%= @event.author.username %>
</div>

app/views/events/show/_teams-container.html.erb
<section id="teams-container">
  <% event.teams.each_with_index do |team, i| %>

    <div class="team-card team-<%= i + 1 %>">

      <h2 class="team-title">
        <%= team.name %>
      </h2>

      <%= render 'events/show/each-players', team: team, event: event, event_player: @event_player, i: i %>

    </div>

  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FutsalCeSoir</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar/index' %>
    <%= yield %>
    <%= render 'layouts/shared/footer' %>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/shared/_footer.html.erb
<footer class="text-center">
  ici mon footer
  <p>Fait par Adam - Un souci, un bug, un conseil à me faire remonter ? Contacte-moi sur mon snap adamneyney ! Ca m'aidera énormément je fais le site seul !</p>
</footer>

app/views/layouts/shared/navbar/_index.html.erb
<% if user_signed_in? %>
  <nav data-controller="navbar">
    <%= render 'layouts/shared/navbar/top' %>
    <%= render 'layouts/shared/navbar/menu' %>
  </nav>
<% end %>

app/views/layouts/shared/navbar/_menu.html.erb
<section id="dark-overlay" class="d-none" data-action="click->navbar#open" data-navbar-target="dark">
</section>
<section id="menu-section" class="d-none close" data-navbar-target="menu">
  <ul id="menu-list">
    <li>
      <%= link_to events_path do %>
        <div class='link'>Accueil</div>
      <% end %>
    </li>

    <li>
      <%= link_to new_event_path do %>
        <div class='link'>Organiser un futsal</div>
      <% end %>
    </li>

    <li>
      <%= link_to events_path do %>
        <div class='link'>Invitation</div>
      <% end %>
    </li>

    <li>
      <%= link_to events_path do %>
        <div class='link'>Mes Amis</div>
      <% end %>
    </li>

    <%# Partial des buttons pour changer entre agent libre et privé %>
    <%= render 'users/free_agent', user: current_user %>

    <li>
      <%= link_to edit_user_registration_path do %>
        <div class='link'>Paramètres du compte</div>
      <% end %>
    </li>

    <li>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <div class='link'>Déconnexion</div>
      <% end %>
    </li>

  </ul>
</section>

app/views/layouts/shared/navbar/_top.html.erb
<section id="navbar-top">

    <div>
      <%= current_user.username if current_user %>
    </div>

    <div>
      <%= link_to root_path do %>
        <%= image_tag 'ballon.png', width: 40 %>
      <% end %>
    </div>

    <div>
      <button class="menu-btn" data-action="click->navbar#open" data-navbar-target="btn">
        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>
      </button>

      <button class="menu-btn d-none" data-action="click->navbar#open" data-navbar-target="btn">
        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 384 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/></svg>
      </button>


    </div>

  </section>

app/views/users/_free_agent.html.erb
 <li id="menu-agent-swap">
 <%= form_with model: user, url: free_agent_true_path, method: :patch, data: { turbo_stream: true }, class: 'form-agent' do |f| %>
  <%= f.hidden_field :free_agent, value: true %>
  <%= f.submit 'Agent libre', class: "btn-agent #{user.free_agent ? "btn-active-left" : "btn-inactive" }" %>
  <% end %>

  <%= form_with model: user, url: free_agent_false_path, method: :patch, class: 'form-agent' do |f| %>
  <%= f.hidden_field :free_agent, value: false %>
  <%= f.submit 'Joueur privé', class: "btn-agent #{user.free_agent ? "btn-inactive" : "btn-active-right" }" %>
  <% end %>
  </li>

app/views/users/free_agent_false.turbo_stream.erb
<%= turbo_stream.replace 'menu-agent-swap' do %>
  <%= render partial: 'users/free_agent', locals: { user: @user } %>
<% end %>

app/views/users/free_agent_true.turbo_stream.erb
<%= turbo_stream.replace 'menu-agent-swap' do %>
  <%= render partial: 'users/free_agent', locals: { user: @user } %>
<% end %>